* re-added docker-compose-no-https.yml to be able to start lasius in …
tegonal/lasius-docker-compose pull request #8
Opened 2024-11-20 06:54 UTC by toggm

…production without self-signed certificate

* cover non-https case in setup script
* auto-generate admin password for mongodb instance

2024-11-20 06:58 UTC, toggm commented
Related to https://github.com/tegonal/Lasius/issues/36

2024-11-26 15:42 UTC, MarcoSteinacher commented on setup.sh
> +  read -rp "Start lasius in https mode (with self-signed certificate)? (y/n) " yn
"self-signed" could be misleading here. Isn't it a Let's Encrypt certificate? When I read self-signed, I think of a certificate that has not been signed by a trusted CA but one that I have signed myself and therefore is not trusted by browsers by default.

2024-12-04 14:31 UTC, MarcoSteinacher requested changes

2024-12-04 14:31 UTC, MarcoSteinacher commented on start.sh
> +if [ -z "$dockerfile"]; then
Missing space before ], which triggers a bash error if $dockerfile is not empty. (The code is working as expected, though.)

2024-12-04 16:19 UTC, MarcoSteinacher approved these changes

2024-12-04 18:17 UTC, merged